logs:
    dir_logs: logs/dual_model/CLEVR/iQAN_Mutan_iBOWIMG
vqa:
    dataset: CLEVR
    dir: data/clevr
    trainsplit: train
    nans: 2000
    maxlength: 30
    minwcount: 0
    nlp: nltk
    pad: right
    add_start: True #whether to add start
    select_questions: True
    ##### concept related settings
    sample_concept: False
    concept_mincount: 30
clevr:
    dir: data/clevr
    arch: resnet152
    mode: noatt
    size: 448
optim:
    lr: 0.0001
    lr_decay: 0.5
    lr_decay_epoch: 30
    batch_size: 512
    epochs: 50
    optimizer: Adam
    weight_decay: 0.00001
## Model Settings
model: 
    arch: Dual_Model_Baseline
    arch_resnet: resnet152
    dim_v: 2048
    dim_q: 1024
    dim_a: 1024
    # VQA module settings for Mutan
    vqa:
        dropout: 0.5
        activation: tanh
    vqg:
        activation: tanh
        dropout: 0.5
        vec2seq:
            nb_layers: 1
            arch: Baseline   # correspond to Fusion
            dim_embedding: 1024
            dim_h: 2400
            activation: relu
            dropout: 0.5
            share_weight: 0 # share the weight of word embedding and word classifier
            nseq: 20
